### ISSUE TITLE
NodeJS 4.2?

### ISSUE THREAD

**Issue by ArchangeGabriel** [babolivier/cozy-archlinux#13]
Just found this in the latest newsletter: https://blog.cozycloud.cc/post/2016/04/06/Migration-to-Node-4

But we where already using 4.4.x on Arch, right? So, why was what, and are we affected in any way by the procedures described in this article?

Thanks!

**Comment by babolivier** [comment]
Hi @ArchangeGabriel,

This package's dependencies are already up to date, so no need for an upgrade. The post linked on the newsletter only concerns Debian-based distros :wink:
