### ISSUE TITLE
Supervisor does not start when 9001 port is already used

### ISSUE THREAD

**Issue by juanwolf** [babolivier/cozy-archlinux#4]
I don't know if it's a proper issue but the installation did not work for me the first time.

I add to configure the /etc/supervisor.conf file to change the port.

Maybe a test during the installation would be useful or just a text to warn the user that this port needs to be available.

**Comment by babolivier** [comment]
Hi @juanwolf and thanks for the feedback.
This is indeed a great idea. I already plan on adding a few tests to the installation process to make it cleaner, I'll add this one to the TODO list

**Comment by juanwolf** [comment]
You're welcome, if you need any help let me know.

**Comment by babolivier** [comment]
A test has been added [here](https://github.com/babolivier/cozy-archlinux/blob/master/standalone/cozy-standalone.install#L39-L43) (for all three packages). I just pushed a new version of the package to this Github repo, and I should push it to AUR very soon.
